CREATE TABLE Address (
    ADDRESS_ID INT PRIMARY KEY,
    ADDRESSLINE1 VARCHAR(255),
    ADDRESSLINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    POSTALCODE VARCHAR(20),
    COUNTRY VARCHAR(100),
    TERRITORY VARCHAR(50)
);

INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('1', '897 Long Airport Avenue', NULL, 'NYC', 'NY', '10022', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('2', '59 rue de l''Abbaye', NULL, 'Reims', NULL, '51100', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('3', '27 rue du Colonel Pierre Avia', NULL, 'Paris', NULL, '75508', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('4', '78934 Hillside Dr.', NULL, 'Pasadena', 'CA', '90003', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('5', '7734 Strong St.', NULL, 'San Francisco', 'CA', NULL, 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('6', '9408 Furth Circle', NULL, 'Burlingame', 'CA', '94217', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('7', '184, chausse de Tournai', NULL, 'Lille', NULL, '59000', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('8', 'Drammen 121, PR 744 Sentrum', NULL, 'Bergen', NULL, 'N 5804', 'Norway', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('9', '5557 North Pendale Street', NULL, 'San Francisco', 'CA', NULL, 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('10', '25, rue Lauriston', NULL, 'Paris', NULL, '75016', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('11', '636 St Kilda Road', 'Level 3', 'Melbourne', 'Victoria', '3004', 'Australia', 'APAC');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('12', '2678 Kingston Rd.', 'Suite 101', 'NYC', 'NY', '10022', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('13', '7476 Moss Rd.', NULL, 'Newark', 'NJ', '94019', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('14', '25593 South Bay Ln.', NULL, 'Bridgewater', 'CT', '97562', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('15', '67, rue des Cinquante Otages', NULL, 'Nantes', NULL, '44000', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('16', '39323 Spinnaker Dr.', NULL, 'Cambridge', 'MA', '51247', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('17', 'Keskuskatu 45', NULL, 'Helsinki', NULL, '21240', 'Finland', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('18', 'Erling Skakkes gate 78', NULL, 'Stavern', NULL, '4110', 'Norway', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('19', '7586 Pompton St.', NULL, 'Allentown', 'PA', '70267', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('20', 'Geislweg 14', NULL, 'Salzburg', NULL, '5020', 'Austria', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('21', 'Monitor Money Building, 815 Pacific Hwy', 'Level 6', 'Chatswood', 'NSW', '2067', 'Australia', 'APAC');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('22', '1785 First Street', NULL, 'New Bedford', 'MA', '50553', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('23', 'Berkeley Gardens 12  Brewery', NULL, 'Liverpool', NULL, 'WX1 6LT', 'UK', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('24', 'C/ Moralzarzal, 86', NULL, 'Madrid', NULL, '28034', 'Spain', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('25', 'Berguvsv„gen  8', NULL, 'Lule', NULL, 'S-958 22', 'Sweden', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('26', 'C/ Araquil, 67', NULL, 'Madrid', NULL, '28023', 'Spain', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('27', 'Bronz Sok., Bronz Apt. 3/6 Tesvikiye', NULL, 'Singapore', NULL, '79903', 'Singapore', 'Japan');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('28', '5905 Pompton St.', 'Suite 750', 'NYC', 'NY', '10022', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('29', '31 Duncan St. West End', NULL, 'South Brisbane', 'Queensland', '4101', 'Australia', 'APAC');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('30', '782 First Street', NULL, 'Philadelphia', 'PA', '71270', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('31', '2, rue du Commerce', NULL, 'Lyon', NULL, '69004', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('32', '1900 Oak St.', NULL, 'Vancouver', 'BC', 'V3F 2K1', 'Canada', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('33', '3675 Furth Circle', NULL, 'Burbank', 'CA', '94019', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('34', '4658 Baden Av.', NULL, 'Cambridge', 'MA', '51247', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('35', '567 North Pendale Street', NULL, 'New Haven', 'CT', '97823', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('36', '2-2-8 Roppongi', NULL, 'Minato-ku', 'Tokyo', '106-0032', 'Japan', 'Japan');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('37', 'Via Monte Bianco 34', NULL, 'Torino', NULL, '10100', 'Italy', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('38', '?kergatan 24', NULL, 'Boras', NULL, 'S-844 67', 'Sweden', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('39', '67, avenue de l''Europe', NULL, 'Versailles', NULL, '78000', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('40', '5677 Strong St.', NULL, 'San Rafael', 'CA', '97562', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('41', '2304 Long Airport Avenue', NULL, 'Nashua', 'NH', '62005', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('42', '7825 Douglas Av.', NULL, 'Brickhaven', 'MA', '58339', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('43', '201 Miller Street', 'Level 15', 'North Sydney', 'NSW', '2060', 'Australia', 'APAC');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('44', '43 rue St. Laurent', NULL, 'Montreal', 'Quebec', 'H1J 1C3', 'Canada', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('45', 'Dojima Avanza 4F, 1-6-20 Dojima, Kita-ku', NULL, 'Osaka', 'Osaka', '530-0003', 'Japan', 'Japan');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('46', '11328 Douglas Av.', NULL, 'Philadelphia', 'PA', '71270', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('47', '54, rue Royale', NULL, 'Nantes', NULL, '44000', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('48', '3758 North Pendale Street', NULL, 'White Plains', 'NY', '24067', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('49', 'Vinb''ltet 34', NULL, 'Kobenhavn', NULL, '1734', 'Denmark', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('50', '35 King George', NULL, 'London', NULL, 'WX3 6FW', 'UK', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('51', '4575 Hillside Dr.', NULL, 'New Bedford', 'MA', '50553', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('52', '1 rue Alsace-Lorraine', NULL, 'Toulouse', NULL, '31000', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('53', '120 Hanover Sq.', NULL, 'London', NULL, 'WA1 1DP', 'UK', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('54', 'Rambla de Catalu¤a, 23', NULL, 'Barcelona', NULL, '8022', 'Spain', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('55', '6047 Douglas Av.', NULL, 'Los Angeles', 'CA', NULL, 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('56', '361 Furth Circle', NULL, 'San Diego', 'CA', '91217', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('57', 'Rue Joseph-Bens 532', NULL, 'Bruxelles', NULL, 'B-1180', 'Belgium', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('58', '23 Tsawassen Blvd.', NULL, 'Tsawassen', 'BC', 'T2F 8M4', 'Canada', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('59', '8616 Spinnaker Dr.', NULL, 'Boston', 'MA', '51003', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('60', 'Garden House Crowther Way', NULL, 'Cowes', 'Isle of Wight', 'PO31 7PJ', 'UK', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('61', 'Torikatu 38', NULL, 'Oulu', NULL, '90110', 'Finland', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('62', '3086 Ingle Ln.', NULL, 'San Jose', 'CA', '94217', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('63', '265, boulevard Charonne', NULL, 'Paris', NULL, '75012', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('64', 'Kirchgasse 6', NULL, 'Graz', NULL, '8010', 'Austria', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('65', '6251 Ingle Ln.', NULL, 'Boston', 'MA', '51003', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('66', 'Village Close - 106 Linden Road Sandown', '2nd Floor', 'Singapore', NULL, '69045', 'Singapore', 'APAC');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('67', '15 McCallum Street - NatWest Center #13-03', NULL, 'Makati City', NULL, '1227 MM', 'Philippines', 'Japan');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('68', '12, rue des Bouchers', NULL, 'Marseille', NULL, '13008', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('69', 'Mehrheimerstr. 369', NULL, 'Koln', NULL, '50739', 'Germany', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('70', 'Grenzacherweg 237', NULL, 'Gensve', NULL, '1203', 'Switzerland', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('71', 'Strada Provinciale 124', NULL, 'Reggio Emilia', NULL, '42100', 'Italy', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('72', '7635 Spinnaker Dr.', NULL, 'Brickhaven', 'MA', '58339', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('73', 'Lyonerstr. 34', NULL, 'Frankfurt', NULL, '60528', 'Germany', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('74', 'Software Engineering Center, SEC Oy', NULL, 'Espoo', NULL, 'FIN-02271', 'Finland', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('75', '4092 Furth Circle', 'Suite 400', 'NYC', 'NY', '10022', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('76', '25 Maiden Lane', 'Floor No. 4', 'Dublin', NULL, '2', 'Ireland', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('77', 'Merchants House, 27-30 Merchant''s Quay', NULL, 'Madrid', NULL, '28023', 'Spain', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('78', 'Fauntleroy Circus', NULL, 'Manchester', NULL, 'EC2 5NT', 'UK', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('79', 'Smagsloget 45', NULL, 'Aaarhus', NULL, '8200', 'Denmark', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('80', '5290 North Pendale Street', 'Suite 200', 'NYC', 'NY', '10022', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('81', '4097 Douglas Av.', NULL, 'Glendale', 'CA', '92561', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('82', 'C/ Romero, 33', NULL, 'Sevilla', NULL, '41101', 'Spain', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('83', '2793 Furth Circle', NULL, 'Brisbane', 'CA', '94217', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('84', '24, place Kluber', NULL, 'Strasbourg', NULL, '67000', 'France', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('85', '8489 Strong St.', NULL, 'Las Vegas', 'NV', '83030', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('86', 'Drammensveien 126 A, PB 744 Sentrum', NULL, 'Oslo', NULL, 'N 0106', 'Norway', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('87', 'Via Ludovico il Moro 22', NULL, 'Bergamo', NULL, '24100', 'Italy', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('88', '7 Allen Street', NULL, 'Glen Waverly', 'Victoria', '3150', 'Australia', 'APAC');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('89', '2440 Pompton St.', NULL, 'Glendale', 'CT', '97561', 'USA', NULL);
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('90', 'Hansastr. 15', NULL, 'Munich', NULL, '80686', 'Germany', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('91', 'Boulevard Tirou, 255', NULL, 'Charleroi', NULL, 'B-6000', 'Belgium', 'EMEA');
INSERT INTO Address (ADDRESS_ID, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY) VALUES ('92', '16780 Pompton St.', NULL, 'Brickhaven', 'MA', '58339', 'USA', NULL);
