CREATE TABLE DomesticCustomer (
    CUSTOMER_ID INT PRIMARY KEY,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID)
);

INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('1');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('4');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('5');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('6');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('9');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('12');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('13');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('14');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('16');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('19');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('22');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('28');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('30');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('33');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('34');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('35');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('40');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('41');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('42');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('46');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('48');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('51');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('55');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('56');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('59');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('62');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('65');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('72');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('75');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('80');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('81');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('83');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('85');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('89');
INSERT INTO DomesticCustomer (CUSTOMER_ID) VALUES ('92');
