CREATE TABLE Product_Line (
    PRODUCTLINE_ID INT PRIMARY KEY,
    PRODUCTLINE_NAME VARCHAR(100)
);

INSERT INTO Product_Line (PRODUCTLINE_ID, PRODUCTLINE_NAME) VALUES ('1', 'Classic Cars');
INSERT INTO Product_Line (PRODUCTLINE_ID, PRODUCTLINE_NAME) VALUES ('2', 'Motorcycles');
INSERT INTO Product_Line (PRODUCTLINE_ID, PRODUCTLINE_NAME) VALUES ('3', 'Planes');
INSERT INTO Product_Line (PRODUCTLINE_ID, PRODUCTLINE_NAME) VALUES ('4', 'Ships');
INSERT INTO Product_Line (PRODUCTLINE_ID, PRODUCTLINE_NAME) VALUES ('5', 'Trains');
INSERT INTO Product_Line (PRODUCTLINE_ID, PRODUCTLINE_NAME) VALUES ('6', 'Trucks and Buses');
INSERT INTO Product_Line (PRODUCTLINE_ID, PRODUCTLINE_NAME) VALUES ('7', 'Vintage Cars');
